# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('added_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
